sets:
  - package: xdrs-core@0.38.0
  # - package: git:https://github.com/flaviostutz/xdrs-core.git@main
    selector:
      files:
        - .xdrs/_core/**
        - AGENTS.md
    output:
      path: .
      gitignore: false
    presets:
      - core
      - basic

  - selector:
      files:
        - .xdrs/agentme/edrs/application/skills/004-select-relevant-xdrs/**
    output:
      path: .
      gitignore: false
    presets:
      - core

  - selector:
      files:
        - .xdrs/agentme/**
    output:
      path: .
      gitignore: false
    presets:
      - basic

  - selector:
      files:
        - .xdrs/index.md
    output:
      path: .
      managed: false
      skipIfExists: true
      gitignore: false
    presets:
      - basic

