"""Ledger -> Portfolio Performance CSV files; extra ledger_* columns keep the export lossless (see import_pp)."""

import json
from collections import Counter
from decimal import Decimal

from portfolio_manager.app import import_pp, ppcsv
from portfolio_manager.app.records import dec
from portfolio_manager.shared.errors import PmError

# type -> (label when cash > 0, label when cash < 0, label when cash == 0)
ACCOUNT_LABELS = {
    "DIVIDEND": ("Dividend", "Dividend", "Dividend"),
    "INTEREST": ("Interest", "Interest Charge", "Interest"),
    "FEE": ("Fees Refund", "Fees", "Fees"),
    "TAX": ("Tax Refund", "Taxes", "Taxes"),
    "DEPOSIT": ("Deposit", "Deposit", "Deposit"),
    "WITHDRAWAL": ("Removal", "Removal", "Removal"),
}
TRANSFER_LABELS = {"TRANSFER_IN": "Transfer (Inbound)", "TRANSFER_OUT": "Transfer (Outbound)"}
TRADE_TYPES = ("BUY", "SELL")
EVENT_FIELDS = (
    "account",
    "time",
    "isin",
    "symbol",
    "name",
    "quantity",
    "currency",
    "cash",
    "fee",
    "tax",
    "ref",
    "price",
    "gross",
    "fx_rate",
    "raw_type",
)
OPENING_POSITION = "OPENING"
OPENING_CASH = "OPENING_CASH"

README_TEXT = """Portfolio Performance import files (generated by `pm export`; do not edit by hand).

Import order in Portfolio Performance (File > Import > CSV files, delimiter ';', encoding UTF-8):
1. securities.csv            type "Securities"
2. create the deposit and securities accounts listed in accounts.csv (columns Cash Account / Securities Account)
3. portfolio-transactions.csv type "Portfolio Transactions"
4. account-transactions.csv  type "Account Transactions"

Notes:
- Columns starting with ledger_ are ignored by Portfolio Performance; they make the files lossless.
- OPENING rows carry the position and cash that existed before the first statement (cost unknown, value 0).
  Portfolio Performance counts the opening Deposit as an external flow; the manage-investment-portfolio analysis does not.
- Dividend withholding tax is only in ledger_tax: the Portfolio Performance CSV import has no tax field for dividends.
- Statement-only accounts (snapshots, value-only) have no transactions; their data is in snapshots.csv and references.csv.
- Exchange Rate is left empty on purpose; the statement rate is in ledger_fx_rate.
"""
DECIMAL_COMMA_NOTE = (
    "- Value, Shares, Fees, Taxes and Gross Amount use ',' as decimal separator (--decimal-comma): "
    "import with a German number format.\n"
)


def cash_account(acct: dict) -> str:
    return f"{acct['id']} ({acct['currency']})"


def _classify(e: dict) -> tuple[str, str]:
    """(target file, Portfolio Performance type) of a ledger event."""
    kind, qty, cash = e["type"], Decimal(e["quantity"]), Decimal(e["cash"])
    if kind in TRADE_TYPES:
        return ppcsv.PORTFOLIO_TRANSACTIONS, kind.title()
    if kind == "SPLIT":
        return ppcsv.PORTFOLIO_TRANSACTIONS, "Delivery (Inbound)" if qty >= 0 else "Delivery (Outbound)"
    if kind in TRANSFER_LABELS:
        return (ppcsv.PORTFOLIO_TRANSACTIONS if qty else ppcsv.ACCOUNT_TRANSACTIONS), TRANSFER_LABELS[kind]
    if kind not in ACCOUNT_LABELS:
        msg = f"cannot export event type {kind!r}"
        raise PmError(msg)
    positive, negative, zero = ACCOUNT_LABELS[kind]
    return ppcsv.ACCOUNT_TRANSACTIONS, positive if cash > 0 else negative if cash < 0 else zero


def _nonzero(value: str) -> str:
    return "" if Decimal(value) == 0 else value


def _ledger_cells(seq: int, kind: str, source: dict) -> dict:
    return {"ledger_seq": seq, "ledger_type": kind, **{f"ledger_{k}": source.get(k) for k in EVENT_FIELDS}}


def _event_row(seq: int, e: dict, currencies: dict) -> tuple[str, dict]:
    target, pp_type = _classify(e)
    qty, cash = Decimal(e["quantity"]), Decimal(e["cash"])
    ccy = currencies.get(e["account"], e["currency"])
    trade = e["type"] in TRADE_TYPES
    row = {
        "Date": e["date"],
        "Time": e["time"],
        "Type": pp_type,
        "Value": "0" if e["type"] == "SPLIT" else dec(abs(cash)),
        "Shares": dec(abs(qty)) if qty else "",
        "ISIN": e["isin"],
        "Ticker Symbol": e["symbol"],
        "Security Name": e["name"],
        "Fees": _nonzero(e["fee"]) if trade else "",
        "Taxes": _nonzero(e["tax"]) if trade else "",
        "Note": e.get("raw_type", ""),
        "Cash Account": f"{e['account']} ({ccy})",
        "Securities Account": e["account"],
        **_ledger_cells(seq, e["type"], e),
    }
    gross = e.get("gross")
    if gross is not None and (e["type"] == "DIVIDEND" or e["currency"] != ccy):
        row["Gross Amount"] = dec(abs(Decimal(gross)))
        row["Currency Gross Amount"] = e["currency"]
    return target, row


def _opening_date(acct_id: str, opening: dict, data: dict) -> str:
    """Opening date, else the first activity of the account (Portfolio Performance needs a date on every row)."""
    if opening.get("date"):
        return opening["date"]
    days = [e["date"] for e in data["events"] if e["account"] == acct_id]
    days += [s["date"] for s in data["snapshots"] if s["account"] == acct_id]
    return min(days, default="")


def _opening_rows(data: dict, currencies: dict) -> tuple[list[dict], list[dict]]:
    """(portfolio rows, account rows) for the cash and positions held before the first statement."""
    portfolio, account = [], []
    for acct_id, opening in sorted(data["accounts"]["openings"].items()):
        day = _opening_date(acct_id, opening, data)
        ccy = currencies.get(acct_id, "")
        base = {"Date": day, "Cash Account": f"{acct_id} ({ccy})", "Securities Account": acct_id}
        if Decimal(opening.get("cash", "0")) != 0:
            account.append(
                {
                    **base,
                    "Type": "Deposit",
                    "Value": dec(abs(Decimal(opening["cash"]))),
                    "Note": "opening cash",
                    **_ledger_cells(0, OPENING_CASH, {"account": acct_id, "cash": opening["cash"]}),
                }
            )
        for i, p in enumerate(opening.get("positions", [])):
            portfolio.append(
                {
                    **base,
                    "Type": "Delivery (Inbound)",
                    "Value": "0",
                    "Shares": p["quantity"],
                    "ISIN": p["isin"],
                    "Ticker Symbol": p["symbol"],
                    "Security Name": p["name"],
                    "Note": "opening position",
                    **_ledger_cells(i, OPENING_POSITION, {"account": acct_id, **p}),
                }
            )
    return portfolio, account


def _pick(values: list[str]) -> str:
    """Most frequent non-empty value; ties go to the alphabetically first."""
    counts = Counter(v for v in values if v)
    return min(counts, key=lambda v: (-counts[v], v)) if counts else ""


def _securities(data: dict, currencies: dict) -> list[dict]:
    seen: dict[str, list[dict]] = {}
    sources = [(e, e["currency"]) for e in data["events"]]
    for acct_id, opening in data["accounts"]["openings"].items():
        sources += [(p, currencies.get(acct_id, "")) for p in opening.get("positions", [])]
    for item, currency in sources:
        key = item["isin"] or item["symbol"]
        if key:
            seen.setdefault(key, []).append({**item, "currency": currency})
    return [
        {
            "ISIN": _pick([i["isin"] for i in items]),
            "Ticker Symbol": _pick([i["symbol"] for i in items]),
            "Security Name": _pick([i["name"] for i in items]),
            "Currency": _pick([i["currency"] for i in items]),
        }
        for _, items in sorted(seen.items())
    ]


def _account_rows(data: dict) -> list[dict]:
    rows = []
    for a in data["accounts"]["accounts"]:
        opening = data["accounts"]["openings"].get(a["id"])
        rows.append(
            {
                "Cash Account": cash_account(a),
                "Securities Account": a["id"],
                "ledger_account": a["id"],
                "ledger_institution": a["institution"],
                "ledger_currency": a["currency"],
                "ledger_mode": a["mode"],
                "ledger_opening_date": (opening or {}).get("date"),
                "ledger_opening_cash": None if opening is None else opening.get("cash", "0"),
            }
        )
    return rows


def _record_json(record: dict) -> str:
    return json.dumps(record, sort_keys=True, ensure_ascii=False, separators=(",", ":"))


def build(data: dict, *, decimal_comma: bool = False) -> dict[str, str]:
    """data: accounts, events, snapshots, references of the ledger. Returns {file name: text}."""
    currencies = {a["id"]: a["currency"] for a in data["accounts"]["accounts"]}
    portfolio, account = _opening_rows(data, currencies)
    for seq, e in enumerate(data["events"]):
        target, row = _event_row(seq, e, currencies)
        (portfolio if target == ppcsv.PORTFOLIO_TRANSACTIONS else account).append(row)
    columns = (*ppcsv.TRANSACTION_COLUMNS, *ppcsv.LEDGER_COLUMNS)
    snapshots = [{**s, "record_json": _record_json(s)} for s in data["snapshots"]]
    references = [{**r, "record_json": _record_json(r)} for r in data["references"]]
    return {
        ppcsv.SECURITIES: ppcsv.dumps(ppcsv.SECURITY_COLUMNS, _securities(data, currencies)),
        ppcsv.ACCOUNTS: ppcsv.dumps(ppcsv.ACCOUNT_COLUMNS, _account_rows(data)),
        ppcsv.PORTFOLIO_TRANSACTIONS: ppcsv.dumps(columns, portfolio, decimal_comma=decimal_comma),
        ppcsv.ACCOUNT_TRANSACTIONS: ppcsv.dumps(columns, account, decimal_comma=decimal_comma),
        ppcsv.SNAPSHOTS: ppcsv.dumps(ppcsv.SNAPSHOT_COLUMNS, snapshots),
        ppcsv.REFERENCES: ppcsv.dumps(ppcsv.REFERENCE_COLUMNS, references),
        ppcsv.README: README_TEXT + (DECIMAL_COMMA_NOTE if decimal_comma else ""),
    }


def verify(data: dict, files: dict[str, str]) -> list[str]:
    """Re-read the files; every section must equal the ledger (so any replay of them gives the same result)."""
    rebuilt = import_pp.read(files)
    return [
        f"{section} read back from the CSV files differ from the ledger"
        for section in ("accounts", "events", "snapshots", "references")
        if rebuilt[section] != data[section]
    ]
